
data temp;
   set casuser.ads_gbx0;

*------------------------------------------------------------*;
* DMCAS Release:         8.5;
* SAS Release:           V.03.05M0P111119;
* Site Number:           70269557;
* Host:                  sas-0001-microsrvcs;
* Encoding:              utf-8;
* Java Encoding:         UTF8;
* Locale:                en_US;
* Project GUID:          5d9cc4c8-250e-4fa6-a512-b462180a59b1;
* Node GUID:             352f2ee5-ed24-46b1-af80-b92f07a37613;
* Generated by:          sint.sedgemon.c;
* Date:                  21JUN2021:19:45:19
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _88IMC907YTMNJ6W0B706Q97Y9;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _4M0XCAS2U7U2B8IJZZWBEKQ8G;
*------------------------------------------------------------*;

* Transformation Method = QUANTILE ;
Label 'BIN_pGB1'n = 'Transformed Predicted Probability: targetGB1=1';
Length 'BIN_pGB1'n $22;
if missing('pGB1'n) then
   'BIN_pGB1'n = '_MISSING_';
else
if 'pGB1'n <= 0.0069386 then
   'BIN_pGB1'n = '01:low-0.0069386';
else 
if 'pGB1'n <= 0.0237735 then
   'BIN_pGB1'n = '02:0.0069386-0.0237735';
else 
if 'pGB1'n <= 0.0664559 then
   'BIN_pGB1'n = '03:0.0237735-0.0664559';
else 
   'BIN_pGB1'n = '04:0.0664559-high';

* Transformation Method = QUANTILE ;
Label 'BIN_pGB2'n = 'Transformed Predicted Probability: targetGB2=1';
Length 'BIN_pGB2'n $22;
if missing('pGB2'n) then
   'BIN_pGB2'n = '_MISSING_';
else
if 'pGB2'n <= 0.0264364 then
   'BIN_pGB2'n = '01:low-0.0264364';
else 
if 'pGB2'n <= 0.0430465 then
   'BIN_pGB2'n = '02:0.0264364-0.0430465';
else 
if 'pGB2'n <= 0.0687592 then
   'BIN_pGB2'n = '03:0.0430465-0.0687592';
else 
   'BIN_pGB2'n = '04:0.0687592-high';

* Transformation Method = QUANTILE ;
Label 'BIN_pIssue'n = 'Transformed Predicted: flg_gb_failure=1';
Length 'BIN_pIssue'n $22;
if missing('pIssue'n) then
   'BIN_pIssue'n = '_MISSING_';
else
if 'pIssue'n <= 0 then
   'BIN_pIssue'n = '01:low-0';
else 
if 'pIssue'n <= 0.0294118 then
   'BIN_pIssue'n = '02:0-0.0294118';
else 
   'BIN_pIssue'n = '04:0.0294118-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumCheck4320'n = 'Transformed SumCheck4320';
Length 'BIN_SumCheck4320'n $22;
if missing('SumCheck4320'n) then
   'BIN_SumCheck4320'n = '_MISSING_';
else
if 'SumCheck4320'n <= 0 then
   'BIN_SumCheck4320'n = '01:low-0';
else 
   'BIN_SumCheck4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumDamage4320'n = 'Transformed SumDamage4320';
Length 'BIN_SumDamage4320'n $22;
if missing('SumDamage4320'n) then
   'BIN_SumDamage4320'n = '_MISSING_';
else
if 'SumDamage4320'n <= 0 then
   'BIN_SumDamage4320'n = '01:low-0';
else 
   'BIN_SumDamage4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumInspect4320'n = 'Transformed SumInspect4320';
Length 'BIN_SumInspect4320'n $22;
if missing('SumInspect4320'n) then
   'BIN_SumInspect4320'n = '_MISSING_';
else
if 'SumInspect4320'n <= 0 then
   'BIN_SumInspect4320'n = '01:low-0';
else 
   'BIN_SumInspect4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumOilPress4320'n = 'Transformed SumOilPress4320';
Length 'BIN_SumOilPress4320'n $22;
if missing('SumOilPress4320'n) then
   'BIN_SumOilPress4320'n = '_MISSING_';
else
if 'SumOilPress4320'n <= 0 then
   'BIN_SumOilPress4320'n = '01:low-0';
else 
   'BIN_SumOilPress4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumOilTemp4320'n = 'Transformed SumOilTemp4320';
Length 'BIN_SumOilTemp4320'n $22;
if missing('SumOilTemp4320'n) then
   'BIN_SumOilTemp4320'n = '_MISSING_';
else
if 'SumOilTemp4320'n <= 0 then
   'BIN_SumOilTemp4320'n = '01:low-0';
else 
   'BIN_SumOilTemp4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumRepair4320'n = 'Transformed SumRepair4320';
Length 'BIN_SumRepair4320'n $22;
if missing('SumRepair4320'n) then
   'BIN_SumRepair4320'n = '_MISSING_';
else
if 'SumRepair4320'n <= 0 then
   'BIN_SumRepair4320'n = '01:low-0';
else 
   'BIN_SumRepair4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumTemp4320'n = 'Transformed SumTemp4320';
Length 'BIN_SumTemp4320'n $22;
if missing('SumTemp4320'n) then
   'BIN_SumTemp4320'n = '_MISSING_';
else
if 'SumTemp4320'n <= 0 then
   'BIN_SumTemp4320'n = '01:low-0';
else 
if 'SumTemp4320'n <= 1 then
   'BIN_SumTemp4320'n = '03:0-1';
else 
   'BIN_SumTemp4320'n = '04:1-high';

* Transformation Method = QUANTILE ;
Label 'BIN_SumTot4320'n = 'Transformed Gearbox Issue Flag';
Length 'BIN_SumTot4320'n $22;
if missing('SumTot4320'n) then
   'BIN_SumTot4320'n = '_MISSING_';
else
if 'SumTot4320'n <= 0 then
   'BIN_SumTot4320'n = '01:low-0';
else 
   'BIN_SumTot4320'n = '04:0-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_air_temp_Max'n = 'Transformed Turbine Air Temperature';
Length 'BIN_tdp_air_temp_Max'n $22;
if missing('tdp_air_temp_Max'n) then
   'BIN_tdp_air_temp_Max'n = '_MISSING_';
else
if 'tdp_air_temp_Max'n <= 26 then
   'BIN_tdp_air_temp_Max'n = '01:low-26';
else 
if 'tdp_air_temp_Max'n <= 31.003332 then
   'BIN_tdp_air_temp_Max'n = '02:26-31.003332';
else 
if 'tdp_air_temp_Max'n <= 36.504341 then
   'BIN_tdp_air_temp_Max'n = '03:31.003332-36.504341';
else 
   'BIN_tdp_air_temp_Max'n = '04:36.504341-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_air_temp_Mean'n = 'Transformed Turbine Air Temperature';
Length 'BIN_tdp_air_temp_Mean'n $22;
if missing('tdp_air_temp_Mean'n) then
   'BIN_tdp_air_temp_Mean'n = '_MISSING_';
else
if 'tdp_air_temp_Mean'n <= 12.257664 then
   'BIN_tdp_air_temp_Mean'n = '01:low-12.257664';
else 
if 'tdp_air_temp_Mean'n <= 19.031173 then
   'BIN_tdp_air_temp_Mean'n = '02:12.257664-19.031173';
else 
if 'tdp_air_temp_Mean'n <= 26.046333 then
   'BIN_tdp_air_temp_Mean'n = '03:19.031173-26.046333';
else 
   'BIN_tdp_air_temp_Mean'n = '04:26.046333-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_air_temp_StdDev'n = 'Transformed Turbine Air Temperature';
Length 'BIN_tdp_air_temp_StdDev'n $22;
if missing('tdp_air_temp_StdDev'n) then
   'BIN_tdp_air_temp_StdDev'n = '_MISSING_';
else
if 'tdp_air_temp_StdDev'n <= 4.131445 then
   'BIN_tdp_air_temp_StdDev'n = '01:low-4.131445';
else 
if 'tdp_air_temp_StdDev'n <= 4.7969767 then
   'BIN_tdp_air_temp_StdDev'n = '02:4.131445-4.7969767';
else 
if 'tdp_air_temp_StdDev'n <= 5.9550206 then
   'BIN_tdp_air_temp_StdDev'n = '03:4.7969767-5.9550206';
else 
   'BIN_tdp_air_temp_StdDev'n = '04:5.9550206-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_1_set_Max'n = 'Transformed Blade Angle 1 Set';
Length 'BIN_tdp_blade_angle_1_set_Max'n $22;
if missing('tdp_blade_angle_1_set_Max'n) then
   'BIN_tdp_blade_angle_1_set_Max'n = '_MISSING_';
else
if 'tdp_blade_angle_1_set_Max'n <= 85 then
   'BIN_tdp_blade_angle_1_set_Max'n = '01:low-85';
else 
   'BIN_tdp_blade_angle_1_set_Max'n = '04:85-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_1_set_Mean'n = 'Transformed Blade Angle 1 Set';
Length 'BIN_tdp_blade_angle_1_set_Mean'n $22;
if missing('tdp_blade_angle_1_set_Mean'n) then
   'BIN_tdp_blade_angle_1_set_Mean'n = '_MISSING_';
else
if 'tdp_blade_angle_1_set_Mean'n <= 4.4755701 then
   'BIN_tdp_blade_angle_1_set_Mean'n = '01:low-4.4755701';
else 
if 'tdp_blade_angle_1_set_Mean'n <= 7.9455917 then
   'BIN_tdp_blade_angle_1_set_Mean'n = '02:4.4755701-7.9455917';
else 
if 'tdp_blade_angle_1_set_Mean'n <= 17.279923 then
   'BIN_tdp_blade_angle_1_set_Mean'n = '03:7.9455917-17.279923';
else 
   'BIN_tdp_blade_angle_1_set_Mean'n = '04:17.279923-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_1_set_StdDev'n = 'Transformed Blade Angle 1 Set';
Length 'BIN_tdp_blade_angle_1_set_StdDev'n $22;
if missing('tdp_blade_angle_1_set_StdDev'n) then
   'BIN_tdp_blade_angle_1_set_StdDev'n = '_MISSING_';
else
if 'tdp_blade_angle_1_set_StdDev'n <= 15.682087 then
   'BIN_tdp_blade_angle_1_set_StdDev'n = '01:low-15.682087';
else 
if 'tdp_blade_angle_1_set_StdDev'n <= 21.417588 then
   'BIN_tdp_blade_angle_1_set_StdDev'n = '02:15.682087-21.417588';
else 
if 'tdp_blade_angle_1_set_StdDev'n <= 28.97281 then
   'BIN_tdp_blade_angle_1_set_StdDev'n = '03:21.417588-28.97281';
else 
   'BIN_tdp_blade_angle_1_set_StdDev'n = '04:28.97281-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_2_set_Max'n = 'Transformed Blade Angle 2 Set';
Length 'BIN_tdp_blade_angle_2_set_Max'n $22;
if missing('tdp_blade_angle_2_set_Max'n) then
   'BIN_tdp_blade_angle_2_set_Max'n = '_MISSING_';
else
if 'tdp_blade_angle_2_set_Max'n <= 85 then
   'BIN_tdp_blade_angle_2_set_Max'n = '01:low-85';
else 
   'BIN_tdp_blade_angle_2_set_Max'n = '04:85-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_2_set_Mean'n = 'Transformed Blade Angle 2 Set';
Length 'BIN_tdp_blade_angle_2_set_Mean'n $22;
if missing('tdp_blade_angle_2_set_Mean'n) then
   'BIN_tdp_blade_angle_2_set_Mean'n = '_MISSING_';
else
if 'tdp_blade_angle_2_set_Mean'n <= 4.4755701 then
   'BIN_tdp_blade_angle_2_set_Mean'n = '01:low-4.4755701';
else 
if 'tdp_blade_angle_2_set_Mean'n <= 7.9455917 then
   'BIN_tdp_blade_angle_2_set_Mean'n = '02:4.4755701-7.9455917';
else 
if 'tdp_blade_angle_2_set_Mean'n <= 17.281219 then
   'BIN_tdp_blade_angle_2_set_Mean'n = '03:7.9455917-17.281219';
else 
   'BIN_tdp_blade_angle_2_set_Mean'n = '04:17.281219-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_2_set_StdDev'n = 'Transformed Blade Angle 2 Set';
Length 'BIN_tdp_blade_angle_2_set_StdDev'n $22;
if missing('tdp_blade_angle_2_set_StdDev'n) then
   'BIN_tdp_blade_angle_2_set_StdDev'n = '_MISSING_';
else
if 'tdp_blade_angle_2_set_StdDev'n <= 15.682087 then
   'BIN_tdp_blade_angle_2_set_StdDev'n = '01:low-15.682087';
else 
if 'tdp_blade_angle_2_set_StdDev'n <= 21.420517 then
   'BIN_tdp_blade_angle_2_set_StdDev'n = '02:15.682087-21.420517';
else 
if 'tdp_blade_angle_2_set_StdDev'n <= 28.97281 then
   'BIN_tdp_blade_angle_2_set_StdDev'n = '03:21.420517-28.97281';
else 
   'BIN_tdp_blade_angle_2_set_StdDev'n = '04:28.97281-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_3_set_Max'n = 'Transformed Blade Angle 3 Set';
Length 'BIN_tdp_blade_angle_3_set_Max'n $22;
if missing('tdp_blade_angle_3_set_Max'n) then
   'BIN_tdp_blade_angle_3_set_Max'n = '_MISSING_';
else
if 'tdp_blade_angle_3_set_Max'n <= 85 then
   'BIN_tdp_blade_angle_3_set_Max'n = '01:low-85';
else 
   'BIN_tdp_blade_angle_3_set_Max'n = '04:85-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_3_set_Mean'n = 'Transformed Blade Angle 3 Set';
Length 'BIN_tdp_blade_angle_3_set_Mean'n $22;
if missing('tdp_blade_angle_3_set_Mean'n) then
   'BIN_tdp_blade_angle_3_set_Mean'n = '_MISSING_';
else
if 'tdp_blade_angle_3_set_Mean'n <= 4.4755701 then
   'BIN_tdp_blade_angle_3_set_Mean'n = '01:low-4.4755701';
else 
if 'tdp_blade_angle_3_set_Mean'n <= 7.9455917 then
   'BIN_tdp_blade_angle_3_set_Mean'n = '02:4.4755701-7.9455917';
else 
if 'tdp_blade_angle_3_set_Mean'n <= 16.767106 then
   'BIN_tdp_blade_angle_3_set_Mean'n = '03:7.9455917-16.767106';
else 
   'BIN_tdp_blade_angle_3_set_Mean'n = '04:16.767106-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_3_set_StdDev'n = 'Transformed Blade Angle 3 Set';
Length 'BIN_tdp_blade_angle_3_set_StdDev'n $22;
if missing('tdp_blade_angle_3_set_StdDev'n) then
   'BIN_tdp_blade_angle_3_set_StdDev'n = '_MISSING_';
else
if 'tdp_blade_angle_3_set_StdDev'n <= 15.488483 then
   'BIN_tdp_blade_angle_3_set_StdDev'n = '01:low-15.488483';
else 
if 'tdp_blade_angle_3_set_StdDev'n <= 21.417588 then
   'BIN_tdp_blade_angle_3_set_StdDev'n = '02:15.488483-21.417588';
else 
if 'tdp_blade_angle_3_set_StdDev'n <= 28.586544 then
   'BIN_tdp_blade_angle_3_set_StdDev'n = '03:21.417588-28.586544';
else 
   'BIN_tdp_blade_angle_3_set_StdDev'n = '04:28.586544-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_Max'n = 'Transformed tdp_blade_angle_Max';
Length 'BIN_tdp_blade_angle_Max'n $22;
if missing('tdp_blade_angle_Max'n) then
   'BIN_tdp_blade_angle_Max'n = '_MISSING_';
else
if 'tdp_blade_angle_Max'n <= 85.041667 then
   'BIN_tdp_blade_angle_Max'n = '01:low-85.041667';
else 
if 'tdp_blade_angle_Max'n <= 85.045 then
   'BIN_tdp_blade_angle_Max'n = '02:85.041667-85.045';
else 
if 'tdp_blade_angle_Max'n <= 85.060037 then
   'BIN_tdp_blade_angle_Max'n = '03:85.045-85.060037';
else 
   'BIN_tdp_blade_angle_Max'n = '04:85.060037-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_Mean'n = 'Transformed tdp_blade_angle_Mean';
Length 'BIN_tdp_blade_angle_Mean'n $22;
if missing('tdp_blade_angle_Mean'n) then
   'BIN_tdp_blade_angle_Mean'n = '_MISSING_';
else
if 'tdp_blade_angle_Mean'n <= 4.457889 then
   'BIN_tdp_blade_angle_Mean'n = '01:low-4.457889';
else 
if 'tdp_blade_angle_Mean'n <= 7.9278585 then
   'BIN_tdp_blade_angle_Mean'n = '02:4.457889-7.9278585';
else 
if 'tdp_blade_angle_Mean'n <= 16.953272 then
   'BIN_tdp_blade_angle_Mean'n = '03:7.9278585-16.953272';
else 
   'BIN_tdp_blade_angle_Mean'n = '04:16.953272-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_StdDev'n = 'Transformed tdp_blade_angle_StdDev';
Length 'BIN_tdp_blade_angle_StdDev'n $22;
if missing('tdp_blade_angle_StdDev'n) then
   'BIN_tdp_blade_angle_StdDev'n = '_MISSING_';
else
if 'tdp_blade_angle_StdDev'n <= 15.695717 then
   'BIN_tdp_blade_angle_StdDev'n = '01:low-15.695717';
else 
if 'tdp_blade_angle_StdDev'n <= 21.377421 then
   'BIN_tdp_blade_angle_StdDev'n = '02:15.695717-21.377421';
else 
if 'tdp_blade_angle_StdDev'n <= 27.8893 then
   'BIN_tdp_blade_angle_StdDev'n = '03:21.377421-27.8893';
else 
   'BIN_tdp_blade_angle_StdDev'n = '04:27.8893-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_Var_Max'n = 'Transformed tdp_blade_angle_Var_Max';
Length 'BIN_tdp_blade_angle_Var_Max'n $22;
if missing('tdp_blade_angle_Var_Max'n) then
   'BIN_tdp_blade_angle_Var_Max'n = '_MISSING_';
else
if 'tdp_blade_angle_Var_Max'n <= 0.9678731 then
   'BIN_tdp_blade_angle_Var_Max'n = '01:low-0.9678731';
else 
if 'tdp_blade_angle_Var_Max'n <= 16.992143 then
   'BIN_tdp_blade_angle_Var_Max'n = '02:0.9678731-16.992143';
else 
if 'tdp_blade_angle_Var_Max'n <= 225.66682 then
   'BIN_tdp_blade_angle_Var_Max'n = '03:16.992143-225.66682';
else 
   'BIN_tdp_blade_angle_Var_Max'n = '04:225.66682-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_Var_Mean'n = 'Transformed tdp_blade_angle_Var_Mean';
Length 'BIN_tdp_blade_angle_Var_Mean'n $22;
if missing('tdp_blade_angle_Var_Mean'n) then
   'BIN_tdp_blade_angle_Var_Mean'n = '_MISSING_';
else
if 'tdp_blade_angle_Var_Mean'n <= 0.0251805 then
   'BIN_tdp_blade_angle_Var_Mean'n = '01:low-0.0251805';
else 
if 'tdp_blade_angle_Var_Mean'n <= 0.0731212 then
   'BIN_tdp_blade_angle_Var_Mean'n = '02:0.0251805-0.0731212';
else 
if 'tdp_blade_angle_Var_Mean'n <= 0.3800877 then
   'BIN_tdp_blade_angle_Var_Mean'n = '03:0.0731212-0.3800877';
else 
   'BIN_tdp_blade_angle_Var_Mean'n = '04:0.3800877-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_blade_angle_Var_StdDev'n = 'Transformed tdp_blade_angle_Var_StdDev';
Length 'BIN_tdp_blade_angle_Var_StdDev'n $22;
if missing('tdp_blade_angle_Var_StdDev'n) then
   'BIN_tdp_blade_angle_Var_StdDev'n = '_MISSING_';
else
if 'tdp_blade_angle_Var_StdDev'n <= 0.0656658 then
   'BIN_tdp_blade_angle_Var_StdDev'n = '01:low-0.0656658';
else 
if 'tdp_blade_angle_Var_StdDev'n <= 0.8101262 then
   'BIN_tdp_blade_angle_Var_StdDev'n = '02:0.0656658-0.8101262';
else 
if 'tdp_blade_angle_Var_StdDev'n <= 8.3880478 then
   'BIN_tdp_blade_angle_Var_StdDev'n = '03:0.8101262-8.3880478';
else 
   'BIN_tdp_blade_angle_Var_StdDev'n = '04:8.3880478-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_gen_speed_Max'n = 'Transformed Generator Speed';
Length 'BIN_tdp_gen_speed_Max'n $22;
if missing('tdp_gen_speed_Max'n) then
   'BIN_tdp_gen_speed_Max'n = '_MISSING_';
else
if 'tdp_gen_speed_Max'n <= 1462 then
   'BIN_tdp_gen_speed_Max'n = '01:low-1462';
else 
if 'tdp_gen_speed_Max'n <= 1470.4843 then
   'BIN_tdp_gen_speed_Max'n = '02:1462-1470.4843';
else 
if 'tdp_gen_speed_Max'n <= 1478.5649 then
   'BIN_tdp_gen_speed_Max'n = '03:1470.4843-1478.5649';
else 
   'BIN_tdp_gen_speed_Max'n = '04:1478.5649-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_gen_speed_Mean'n = 'Transformed Generator Speed';
Length 'BIN_tdp_gen_speed_Mean'n $22;
if missing('tdp_gen_speed_Mean'n) then
   'BIN_tdp_gen_speed_Mean'n = '_MISSING_';
else
if 'tdp_gen_speed_Mean'n <= 901.09887 then
   'BIN_tdp_gen_speed_Mean'n = '01:low-901.09887';
else 
if 'tdp_gen_speed_Mean'n <= 1024.8713 then
   'BIN_tdp_gen_speed_Mean'n = '02:901.09887-1024.8713';
else 
if 'tdp_gen_speed_Mean'n <= 1105.7503 then
   'BIN_tdp_gen_speed_Mean'n = '03:1024.8713-1105.7503';
else 
   'BIN_tdp_gen_speed_Mean'n = '04:1105.7503-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_gen_speed_StdDev'n = 'Transformed Generator Speed';
Length 'BIN_tdp_gen_speed_StdDev'n $22;
if missing('tdp_gen_speed_StdDev'n) then
   'BIN_tdp_gen_speed_StdDev'n = '_MISSING_';
else
if 'tdp_gen_speed_StdDev'n <= 323.54881 then
   'BIN_tdp_gen_speed_StdDev'n = '01:low-323.54881';
else 
if 'tdp_gen_speed_StdDev'n <= 384.7506 then
   'BIN_tdp_gen_speed_StdDev'n = '02:323.54881-384.7506';
else 
if 'tdp_gen_speed_StdDev'n <= 456.62114 then
   'BIN_tdp_gen_speed_StdDev'n = '03:384.7506-456.62114';
else 
   'BIN_tdp_gen_speed_StdDev'n = '04:456.62114-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_hydraulic_pressure_Max'n = 'Transformed Hydraulic Pressure';
Length 'BIN_tdp_hydraulic_pressure_Max'n $22;
if missing('tdp_hydraulic_pressure_Max'n) then
   'BIN_tdp_hydraulic_pressure_Max'n = '_MISSING_';
else
if 'tdp_hydraulic_pressure_Max'n <= 74.630844 then
   'BIN_tdp_hydraulic_pressure_Max'n = '01:low-74.630844';
else 
if 'tdp_hydraulic_pressure_Max'n <= 79.40656 then
   'BIN_tdp_hydraulic_pressure_Max'n = '02:74.630844-79.40656';
else 
if 'tdp_hydraulic_pressure_Max'n <= 83.97973 then
   'BIN_tdp_hydraulic_pressure_Max'n = '03:79.40656-83.97973';
else 
   'BIN_tdp_hydraulic_pressure_Max'n = '04:83.97973-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_hydraulic_pressure_Mean'n = 'Transformed Hydraulic Pressure';
Length 'BIN_tdp_hydraulic_pressure_Mean'n $22;
if missing('tdp_hydraulic_pressure_Mean'n) then
   'BIN_tdp_hydraulic_pressure_Mean'n = '_MISSING_';
else
if 'tdp_hydraulic_pressure_Mean'n <= 70.348768 then
   'BIN_tdp_hydraulic_pressure_Mean'n = '01:low-70.348768';
else 
if 'tdp_hydraulic_pressure_Mean'n <= 73.741916 then
   'BIN_tdp_hydraulic_pressure_Mean'n = '02:70.348768-73.741916';
else 
if 'tdp_hydraulic_pressure_Mean'n <= 77.310079 then
   'BIN_tdp_hydraulic_pressure_Mean'n = '03:73.741916-77.310079';
else 
   'BIN_tdp_hydraulic_pressure_Mean'n = '04:77.310079-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_hydraulic_pressure_StdDe'n = 'Transformed Hydraulic Pressure';
Length 'BIN_tdp_hydraulic_pressure_StdDe'n $22;
if missing('tdp_hydraulic_pressure_StdDev'n) then
   'BIN_tdp_hydraulic_pressure_StdDe'n = '_MISSING_';
else
if 'tdp_hydraulic_pressure_StdDev'n <= 1.5292394 then
   'BIN_tdp_hydraulic_pressure_StdDe'n = '01:low-1.5292394';
else 
if 'tdp_hydraulic_pressure_StdDev'n <= 2.1639638 then
   'BIN_tdp_hydraulic_pressure_StdDe'n = '02:1.5292394-2.1639638';
else 
if 'tdp_hydraulic_pressure_StdDev'n <= 3.5083162 then
   'BIN_tdp_hydraulic_pressure_StdDe'n = '03:2.1639638-3.5083162';
else 
   'BIN_tdp_hydraulic_pressure_StdDe'n = '04:3.5083162-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_power_factor_Mean'n = 'Transformed Power Factor';
Length 'BIN_tdp_power_factor_Mean'n $22;
if missing('tdp_power_factor_Mean'n) then
   'BIN_tdp_power_factor_Mean'n = '_MISSING_';
else
if 'tdp_power_factor_Mean'n <= 0.1981973 then
   'BIN_tdp_power_factor_Mean'n = '01:low-0.1981973';
else 
if 'tdp_power_factor_Mean'n <= 0.4309784 then
   'BIN_tdp_power_factor_Mean'n = '02:0.1981973-0.4309784';
else 
if 'tdp_power_factor_Mean'n <= 0.8433717 then
   'BIN_tdp_power_factor_Mean'n = '03:0.4309784-0.8433717';
else 
   'BIN_tdp_power_factor_Mean'n = '04:0.8433717-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_power_factor_StdDev'n = 'Transformed Power Factor';
Length 'BIN_tdp_power_factor_StdDev'n $22;
if missing('tdp_power_factor_StdDev'n) then
   'BIN_tdp_power_factor_StdDev'n = '_MISSING_';
else
if 'tdp_power_factor_StdDev'n <= 0.1996004 then
   'BIN_tdp_power_factor_StdDev'n = '01:low-0.1996004';
else 
if 'tdp_power_factor_StdDev'n <= 0.7811694 then
   'BIN_tdp_power_factor_StdDev'n = '02:0.1996004-0.7811694';
else 
if 'tdp_power_factor_StdDev'n <= 0.8619126 then
   'BIN_tdp_power_factor_StdDev'n = '03:0.7811694-0.8619126';
else 
   'BIN_tdp_power_factor_StdDev'n = '04:0.8619126-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_ResidPower_Max'n = 'Transformed Resid Power Pred by Phase Voltage';
Length 'BIN_tdp_ResidPower_Max'n $22;
if missing('tdp_ResidPower_Max'n) then
   'BIN_tdp_ResidPower_Max'n = '_MISSING_';
else
if 'tdp_ResidPower_Max'n <= 27.158295 then
   'BIN_tdp_ResidPower_Max'n = '01:low-27.158295';
else 
if 'tdp_ResidPower_Max'n <= 28.487963 then
   'BIN_tdp_ResidPower_Max'n = '02:27.158295-28.487963';
else 
if 'tdp_ResidPower_Max'n <= 59.589863 then
   'BIN_tdp_ResidPower_Max'n = '03:28.487963-59.589863';
else 
   'BIN_tdp_ResidPower_Max'n = '04:59.589863-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_ResidPower_Mean'n = 'Transformed Resid Power Pred by Phase Voltage';
Length 'BIN_tdp_ResidPower_Mean'n $22;
if missing('tdp_ResidPower_Mean'n) then
   'BIN_tdp_ResidPower_Mean'n = '_MISSING_';
else
if 'tdp_ResidPower_Mean'n <= -41.5623 then
   'BIN_tdp_ResidPower_Mean'n = '01:low--41.5623';
else 
if 'tdp_ResidPower_Mean'n <= -23.46647 then
   'BIN_tdp_ResidPower_Mean'n = '02:-41.5623--23.46647';
else 
if 'tdp_ResidPower_Mean'n <= -5.782093 then
   'BIN_tdp_ResidPower_Mean'n = '03:-23.46647--5.782093';
else 
   'BIN_tdp_ResidPower_Mean'n = '04:-5.782093-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_ResidPower_StdDev'n = 'Transformed Resid Power Pred by Phase Voltage';
Length 'BIN_tdp_ResidPower_StdDev'n $22;
if missing('tdp_ResidPower_StdDev'n) then
   'BIN_tdp_ResidPower_StdDev'n = '_MISSING_';
else
if 'tdp_ResidPower_StdDev'n <= 41.459978 then
   'BIN_tdp_ResidPower_StdDev'n = '01:low-41.459978';
else 
if 'tdp_ResidPower_StdDev'n <= 56.580964 then
   'BIN_tdp_ResidPower_StdDev'n = '02:41.459978-56.580964';
else 
if 'tdp_ResidPower_StdDev'n <= 76.252744 then
   'BIN_tdp_ResidPower_StdDev'n = '03:56.580964-76.252744';
else 
   'BIN_tdp_ResidPower_StdDev'n = '04:76.252744-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_state_fault_Max'n = 'Transformed State Fault';
Length 'BIN_tdp_state_fault_Max'n $22;
if missing('tdp_state_fault_Max'n) then
   'BIN_tdp_state_fault_Max'n = '_MISSING_';
else
if 'tdp_state_fault_Max'n <= 7 then
   'BIN_tdp_state_fault_Max'n = '01:low-7';
else 
if 'tdp_state_fault_Max'n <= 837.1964 then
   'BIN_tdp_state_fault_Max'n = '02:7-837.1964';
else 
if 'tdp_state_fault_Max'n <= 1179 then
   'BIN_tdp_state_fault_Max'n = '03:837.1964-1179';
else 
   'BIN_tdp_state_fault_Max'n = '04:1179-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_state_fault_Mean'n = 'Transformed State Fault';
Length 'BIN_tdp_state_fault_Mean'n $22;
if missing('tdp_state_fault_Mean'n) then
   'BIN_tdp_state_fault_Mean'n = '_MISSING_';
else
if 'tdp_state_fault_Mean'n <= 2.1856836 then
   'BIN_tdp_state_fault_Mean'n = '01:low-2.1856836';
else 
if 'tdp_state_fault_Mean'n <= 4.3298239 then
   'BIN_tdp_state_fault_Mean'n = '02:2.1856836-4.3298239';
else 
if 'tdp_state_fault_Mean'n <= 28.581 then
   'BIN_tdp_state_fault_Mean'n = '03:4.3298239-28.581';
else 
   'BIN_tdp_state_fault_Mean'n = '04:28.581-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_state_fault_StdDev'n = 'Transformed State Fault';
Length 'BIN_tdp_state_fault_StdDev'n $22;
if missing('tdp_state_fault_StdDev'n) then
   'BIN_tdp_state_fault_StdDev'n = '_MISSING_';
else
if 'tdp_state_fault_StdDev'n <= 0.8545048 then
   'BIN_tdp_state_fault_StdDev'n = '01:low-0.8545048';
else 
if 'tdp_state_fault_StdDev'n <= 37.043268 then
   'BIN_tdp_state_fault_StdDev'n = '02:0.8545048-37.043268';
else 
if 'tdp_state_fault_StdDev'n <= 157.70801 then
   'BIN_tdp_state_fault_StdDev'n = '03:37.043268-157.70801';
else 
   'BIN_tdp_state_fault_StdDev'n = '04:157.70801-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gearbox_bearing_Max'n = 'Transformed Gearbox Shaft Bearing Temperature';
Length 'BIN_tdp_temp_gearbox_bearing_Max'n $22;
if missing('tdp_temp_gearbox_bearing_Max'n) then
   'BIN_tdp_temp_gearbox_bearing_Max'n = '_MISSING_';
else
if 'tdp_temp_gearbox_bearing_Max'n <= 64.79936 then
   'BIN_tdp_temp_gearbox_bearing_Max'n = '01:low-64.79936';
else 
if 'tdp_temp_gearbox_bearing_Max'n <= 66 then
   'BIN_tdp_temp_gearbox_bearing_Max'n = '02:64.79936-66';
else 
if 'tdp_temp_gearbox_bearing_Max'n <= 68 then
   'BIN_tdp_temp_gearbox_bearing_Max'n = '03:66-68';
else 
   'BIN_tdp_temp_gearbox_bearing_Max'n = '04:68-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gearbox_bearing_Mea'n = 'Transformed Gearbox Shaft Bearing Temperature';
Length 'BIN_tdp_temp_gearbox_bearing_Mea'n $22;
if missing('tdp_temp_gearbox_bearing_Mean'n) then
   'BIN_tdp_temp_gearbox_bearing_Mea'n = '_MISSING_';
else
if 'tdp_temp_gearbox_bearing_Mean'n <= 55.452913 then
   'BIN_tdp_temp_gearbox_bearing_Mea'n = '01:low-55.452913';
else 
if 'tdp_temp_gearbox_bearing_Mean'n <= 58.805855 then
   'BIN_tdp_temp_gearbox_bearing_Mea'n = '02:55.452913-58.805855';
else 
if 'tdp_temp_gearbox_bearing_Mean'n <= 60.812254 then
   'BIN_tdp_temp_gearbox_bearing_Mea'n = '03:58.805855-60.812254';
else 
   'BIN_tdp_temp_gearbox_bearing_Mea'n = '04:60.812254-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gearbox_bearin_StdD'n = 'Transformed Gearbox Shaft Bearing Temperature';
Length 'BIN_tdp_temp_gearbox_bearin_StdD'n $22;
if missing('tdp_temp_gearbox_bearin_StdDev'n) then
   'BIN_tdp_temp_gearbox_bearin_StdD'n = '_MISSING_';
else
if 'tdp_temp_gearbox_bearin_StdDev'n <= 3.7395043 then
   'BIN_tdp_temp_gearbox_bearin_StdD'n = '01:low-3.7395043';
else 
if 'tdp_temp_gearbox_bearin_StdDev'n <= 5.5180425 then
   'BIN_tdp_temp_gearbox_bearin_StdD'n = '02:3.7395043-5.5180425';
else 
if 'tdp_temp_gearbox_bearin_StdDev'n <= 7.4062441 then
   'BIN_tdp_temp_gearbox_bearin_StdD'n = '03:5.5180425-7.4062441';
else 
   'BIN_tdp_temp_gearbox_bearin_StdD'n = '04:7.4062441-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gearbox_oil_Max'n = 'Transformed Gearbox Oil Temperature';
Length 'BIN_tdp_temp_gearbox_oil_Max'n $22;
if missing('tdp_temp_gearbox_oil_Max'n) then
   'BIN_tdp_temp_gearbox_oil_Max'n = '_MISSING_';
else
if 'tdp_temp_gearbox_oil_Max'n <= 59 then
   'BIN_tdp_temp_gearbox_oil_Max'n = '01:low-59';
else 
if 'tdp_temp_gearbox_oil_Max'n <= 59.91591 then
   'BIN_tdp_temp_gearbox_oil_Max'n = '02:59-59.91591';
else 
if 'tdp_temp_gearbox_oil_Max'n <= 60 then
   'BIN_tdp_temp_gearbox_oil_Max'n = '03:59.91591-60';
else 
   'BIN_tdp_temp_gearbox_oil_Max'n = '04:60-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gearbox_oil_Mean'n = 'Transformed Gearbox Oil Temperature';
Length 'BIN_tdp_temp_gearbox_oil_Mean'n $22;
if missing('tdp_temp_gearbox_oil_Mean'n) then
   'BIN_tdp_temp_gearbox_oil_Mean'n = '_MISSING_';
else
if 'tdp_temp_gearbox_oil_Mean'n <= 50.856611 then
   'BIN_tdp_temp_gearbox_oil_Mean'n = '01:low-50.856611';
else 
if 'tdp_temp_gearbox_oil_Mean'n <= 53.862107 then
   'BIN_tdp_temp_gearbox_oil_Mean'n = '02:50.856611-53.862107';
else 
if 'tdp_temp_gearbox_oil_Mean'n <= 56.212936 then
   'BIN_tdp_temp_gearbox_oil_Mean'n = '03:53.862107-56.212936';
else 
   'BIN_tdp_temp_gearbox_oil_Mean'n = '04:56.212936-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gearbox_oil_StdDev'n = 'Transformed Gearbox Oil Temperature';
Length 'BIN_tdp_temp_gearbox_oil_StdDev'n $22;
if missing('tdp_temp_gearbox_oil_StdDev'n) then
   'BIN_tdp_temp_gearbox_oil_StdDev'n = '_MISSING_';
else
if 'tdp_temp_gearbox_oil_StdDev'n <= 2.6992893 then
   'BIN_tdp_temp_gearbox_oil_StdDev'n = '01:low-2.6992893';
else 
if 'tdp_temp_gearbox_oil_StdDev'n <= 3.5323416 then
   'BIN_tdp_temp_gearbox_oil_StdDev'n = '02:2.6992893-3.5323416';
else 
if 'tdp_temp_gearbox_oil_StdDev'n <= 5.301175 then
   'BIN_tdp_temp_gearbox_oil_StdDev'n = '03:3.5323416-5.301175';
else 
   'BIN_tdp_temp_gearbox_oil_StdDev'n = '04:5.301175-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_air_cooler_Max'n = 'Transformed Temperature Generator Air Cooler';
Length 'BIN_tdp_temp_gen_air_cooler_Max'n $22;
if missing('tdp_temp_gen_air_cooler_Max'n) then
   'BIN_tdp_temp_gen_air_cooler_Max'n = '_MISSING_';
else
if 'tdp_temp_gen_air_cooler_Max'n <= 57 then
   'BIN_tdp_temp_gen_air_cooler_Max'n = '01:low-57';
else 
if 'tdp_temp_gen_air_cooler_Max'n <= 64 then
   'BIN_tdp_temp_gen_air_cooler_Max'n = '02:57-64';
else 
if 'tdp_temp_gen_air_cooler_Max'n <= 70 then
   'BIN_tdp_temp_gen_air_cooler_Max'n = '03:64-70';
else 
   'BIN_tdp_temp_gen_air_cooler_Max'n = '04:70-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_air_cooler_Mean'n = 'Transformed Temperature Generator Air Cooler';
Length 'BIN_tdp_temp_gen_air_cooler_Mean'n $22;
if missing('tdp_temp_gen_air_cooler_Mean'n) then
   'BIN_tdp_temp_gen_air_cooler_Mean'n = '_MISSING_';
else
if 'tdp_temp_gen_air_cooler_Mean'n <= 36.351164 then
   'BIN_tdp_temp_gen_air_cooler_Mean'n = '01:low-36.351164';
else 
if 'tdp_temp_gen_air_cooler_Mean'n <= 41.343564 then
   'BIN_tdp_temp_gen_air_cooler_Mean'n = '02:36.351164-41.343564';
else 
if 'tdp_temp_gen_air_cooler_Mean'n <= 46.426967 then
   'BIN_tdp_temp_gen_air_cooler_Mean'n = '03:41.343564-46.426967';
else 
   'BIN_tdp_temp_gen_air_cooler_Mean'n = '04:46.426967-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_air_cooler_StdD'n = 'Transformed Temperature Generator Air Cooler';
Length 'BIN_tdp_temp_gen_air_cooler_StdD'n $22;
if missing('tdp_temp_gen_air_cooler_StdDev'n) then
   'BIN_tdp_temp_gen_air_cooler_StdD'n = '_MISSING_';
else
if 'tdp_temp_gen_air_cooler_StdDev'n <= 6.2269503 then
   'BIN_tdp_temp_gen_air_cooler_StdD'n = '01:low-6.2269503';
else 
if 'tdp_temp_gen_air_cooler_StdDev'n <= 8.1137655 then
   'BIN_tdp_temp_gen_air_cooler_StdD'n = '02:6.2269503-8.1137655';
else 
if 'tdp_temp_gen_air_cooler_StdDev'n <= 10.085745 then
   'BIN_tdp_temp_gen_air_cooler_StdD'n = '03:8.1137655-10.085745';
else 
   'BIN_tdp_temp_gen_air_cooler_StdD'n = '04:10.085745-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_bearing_de_Max'n = 'Transformed Temperature Generator Bearing DE';
Length 'BIN_tdp_temp_gen_bearing_de_Max'n $22;
if missing('tdp_temp_gen_bearing_de_Max'n) then
   'BIN_tdp_temp_gen_bearing_de_Max'n = '_MISSING_';
else
if 'tdp_temp_gen_bearing_de_Max'n <= 39 then
   'BIN_tdp_temp_gen_bearing_de_Max'n = '01:low-39';
else 
if 'tdp_temp_gen_bearing_de_Max'n <= 43 then
   'BIN_tdp_temp_gen_bearing_de_Max'n = '02:39-43';
else 
if 'tdp_temp_gen_bearing_de_Max'n <= 48 then
   'BIN_tdp_temp_gen_bearing_de_Max'n = '03:43-48';
else 
   'BIN_tdp_temp_gen_bearing_de_Max'n = '04:48-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_bearing_de_Mean'n = 'Transformed Temperature Generator Bearing DE';
Length 'BIN_tdp_temp_gen_bearing_de_Mean'n $22;
if missing('tdp_temp_gen_bearing_de_Mean'n) then
   'BIN_tdp_temp_gen_bearing_de_Mean'n = '_MISSING_';
else
if 'tdp_temp_gen_bearing_de_Mean'n <= 27.262103 then
   'BIN_tdp_temp_gen_bearing_de_Mean'n = '01:low-27.262103';
else 
if 'tdp_temp_gen_bearing_de_Mean'n <= 32.413712 then
   'BIN_tdp_temp_gen_bearing_de_Mean'n = '02:27.262103-32.413712';
else 
if 'tdp_temp_gen_bearing_de_Mean'n <= 36.96264 then
   'BIN_tdp_temp_gen_bearing_de_Mean'n = '03:32.413712-36.96264';
else 
   'BIN_tdp_temp_gen_bearing_de_Mean'n = '04:36.96264-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_bearing_de_StdD'n = 'Transformed Temperature Generator Bearing DE';
Length 'BIN_tdp_temp_gen_bearing_de_StdD'n $22;
if missing('tdp_temp_gen_bearing_de_StdDev'n) then
   'BIN_tdp_temp_gen_bearing_de_StdD'n = '_MISSING_';
else
if 'tdp_temp_gen_bearing_de_StdDev'n <= 3.5527253 then
   'BIN_tdp_temp_gen_bearing_de_StdD'n = '01:low-3.5527253';
else 
if 'tdp_temp_gen_bearing_de_StdDev'n <= 4.5612581 then
   'BIN_tdp_temp_gen_bearing_de_StdD'n = '02:3.5527253-4.5612581';
else 
if 'tdp_temp_gen_bearing_de_StdDev'n <= 5.4276391 then
   'BIN_tdp_temp_gen_bearing_de_StdD'n = '03:4.5612581-5.4276391';
else 
   'BIN_tdp_temp_gen_bearing_de_StdD'n = '04:5.4276391-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_bearing_nde_Max'n = 'Transformed Temperature Generator Bearing NDE';
Length 'BIN_tdp_temp_gen_bearing_nde_Max'n $22;
if missing('tdp_temp_gen_bearing_nde_Max'n) then
   'BIN_tdp_temp_gen_bearing_nde_Max'n = '_MISSING_';
else
if 'tdp_temp_gen_bearing_nde_Max'n <= 43 then
   'BIN_tdp_temp_gen_bearing_nde_Max'n = '01:low-43';
else 
if 'tdp_temp_gen_bearing_nde_Max'n <= 49 then
   'BIN_tdp_temp_gen_bearing_nde_Max'n = '02:43-49';
else 
if 'tdp_temp_gen_bearing_nde_Max'n <= 55 then
   'BIN_tdp_temp_gen_bearing_nde_Max'n = '03:49-55';
else 
   'BIN_tdp_temp_gen_bearing_nde_Max'n = '04:55-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_bearing_nde_Mea'n = 'Transformed Temperature Generator Bearing NDE';
Length 'BIN_tdp_temp_gen_bearing_nde_Mea'n $22;
if missing('tdp_temp_gen_bearing_nde_Mean'n) then
   'BIN_tdp_temp_gen_bearing_nde_Mea'n = '_MISSING_';
else
if 'tdp_temp_gen_bearing_nde_Mean'n <= 30.769425 then
   'BIN_tdp_temp_gen_bearing_nde_Mea'n = '01:low-30.769425';
else 
if 'tdp_temp_gen_bearing_nde_Mean'n <= 35.493856 then
   'BIN_tdp_temp_gen_bearing_nde_Mea'n = '02:30.769425-35.493856';
else 
if 'tdp_temp_gen_bearing_nde_Mean'n <= 40.602009 then
   'BIN_tdp_temp_gen_bearing_nde_Mea'n = '03:35.493856-40.602009';
else 
   'BIN_tdp_temp_gen_bearing_nde_Mea'n = '04:40.602009-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_gen_bearing_nd_StdD'n = 'Transformed Temperature Generator Bearing NDE';
Length 'BIN_tdp_temp_gen_bearing_nd_StdD'n $22;
if missing('tdp_temp_gen_bearing_nd_StdDev'n) then
   'BIN_tdp_temp_gen_bearing_nd_StdD'n = '_MISSING_';
else
if 'tdp_temp_gen_bearing_nd_StdDev'n <= 3.8178464 then
   'BIN_tdp_temp_gen_bearing_nd_StdD'n = '01:low-3.8178464';
else 
if 'tdp_temp_gen_bearing_nd_StdDev'n <= 5.2175668 then
   'BIN_tdp_temp_gen_bearing_nd_StdD'n = '02:3.8178464-5.2175668';
else 
if 'tdp_temp_gen_bearing_nd_StdDev'n <= 6.7887379 then
   'BIN_tdp_temp_gen_bearing_nd_StdD'n = '03:5.2175668-6.7887379';
else 
   'BIN_tdp_temp_gen_bearing_nd_StdD'n = '04:6.7887379-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_main_bearing_Max'n = 'Transformed Temperature Main Bearing';
Length 'BIN_tdp_temp_main_bearing_Max'n $22;
if missing('tdp_temp_main_bearing_Max'n) then
   'BIN_tdp_temp_main_bearing_Max'n = '_MISSING_';
else
if 'tdp_temp_main_bearing_Max'n <= 31 then
   'BIN_tdp_temp_main_bearing_Max'n = '01:low-31';
else 
if 'tdp_temp_main_bearing_Max'n <= 36 then
   'BIN_tdp_temp_main_bearing_Max'n = '02:31-36';
else 
if 'tdp_temp_main_bearing_Max'n <= 39.99024 then
   'BIN_tdp_temp_main_bearing_Max'n = '03:36-39.99024';
else 
   'BIN_tdp_temp_main_bearing_Max'n = '04:39.99024-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_main_bearing_Mean'n = 'Transformed Temperature Main Bearing';
Length 'BIN_tdp_temp_main_bearing_Mean'n $22;
if missing('tdp_temp_main_bearing_Mean'n) then
   'BIN_tdp_temp_main_bearing_Mean'n = '_MISSING_';
else
if 'tdp_temp_main_bearing_Mean'n <= 23.034364 then
   'BIN_tdp_temp_main_bearing_Mean'n = '01:low-23.034364';
else 
if 'tdp_temp_main_bearing_Mean'n <= 28.319051 then
   'BIN_tdp_temp_main_bearing_Mean'n = '02:23.034364-28.319051';
else 
if 'tdp_temp_main_bearing_Mean'n <= 33.300154 then
   'BIN_tdp_temp_main_bearing_Mean'n = '03:28.319051-33.300154';
else 
   'BIN_tdp_temp_main_bearing_Mean'n = '04:33.300154-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_temp_main_bearing_StdDev'n = 'Transformed Temperature Main Bearing';
Length 'BIN_tdp_temp_main_bearing_StdDev'n $22;
if missing('tdp_temp_main_bearing_StdDev'n) then
   'BIN_tdp_temp_main_bearing_StdDev'n = '_MISSING_';
else
if 'tdp_temp_main_bearing_StdDev'n <= 2.2599004 then
   'BIN_tdp_temp_main_bearing_StdDev'n = '01:low-2.2599004';
else 
if 'tdp_temp_main_bearing_StdDev'n <= 3.2003676 then
   'BIN_tdp_temp_main_bearing_StdDev'n = '02:2.2599004-3.2003676';
else 
if 'tdp_temp_main_bearing_StdDev'n <= 4.7759053 then
   'BIN_tdp_temp_main_bearing_StdDev'n = '03:3.2003676-4.7759053';
else 
   'BIN_tdp_temp_main_bearing_StdDev'n = '04:4.7759053-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_tower_acceleration_Max'n = 'Transformed Tower Acceleration';
Length 'BIN_tdp_tower_acceleration_Max'n $22;
if missing('tdp_tower_acceleration_Max'n) then
   'BIN_tdp_tower_acceleration_Max'n = '_MISSING_';
else
if 'tdp_tower_acceleration_Max'n <= 264.5026 then
   'BIN_tdp_tower_acceleration_Max'n = '01:low-264.5026';
else 
if 'tdp_tower_acceleration_Max'n <= 363.03043 then
   'BIN_tdp_tower_acceleration_Max'n = '02:264.5026-363.03043';
else 
if 'tdp_tower_acceleration_Max'n <= 634.9294 then
   'BIN_tdp_tower_acceleration_Max'n = '03:363.03043-634.9294';
else 
   'BIN_tdp_tower_acceleration_Max'n = '04:634.9294-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_tower_acceleration_Mean'n = 'Transformed Tower Acceleration';
Length 'BIN_tdp_tower_acceleration_Mean'n $22;
if missing('tdp_tower_acceleration_Mean'n) then
   'BIN_tdp_tower_acceleration_Mean'n = '_MISSING_';
else
if 'tdp_tower_acceleration_Mean'n <= 47.888122 then
   'BIN_tdp_tower_acceleration_Mean'n = '01:low-47.888122';
else 
if 'tdp_tower_acceleration_Mean'n <= 58.352858 then
   'BIN_tdp_tower_acceleration_Mean'n = '02:47.888122-58.352858';
else 
if 'tdp_tower_acceleration_Mean'n <= 72.257673 then
   'BIN_tdp_tower_acceleration_Mean'n = '03:58.352858-72.257673';
else 
   'BIN_tdp_tower_acceleration_Mean'n = '04:72.257673-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_tower_acceleration_StdDe'n = 'Transformed Tower Acceleration';
Length 'BIN_tdp_tower_acceleration_StdDe'n $22;
if missing('tdp_tower_acceleration_StdDev'n) then
   'BIN_tdp_tower_acceleration_StdDe'n = '_MISSING_';
else
if 'tdp_tower_acceleration_StdDev'n <= 34.220379 then
   'BIN_tdp_tower_acceleration_StdDe'n = '01:low-34.220379';
else 
if 'tdp_tower_acceleration_StdDev'n <= 46.124838 then
   'BIN_tdp_tower_acceleration_StdDe'n = '02:34.220379-46.124838';
else 
if 'tdp_tower_acceleration_StdDev'n <= 66.943191 then
   'BIN_tdp_tower_acceleration_StdDe'n = '03:46.124838-66.943191';
else 
   'BIN_tdp_tower_acceleration_StdDe'n = '04:66.943191-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_turbine_power_Max'n = 'Transformed Turbine Power';
Length 'BIN_tdp_turbine_power_Max'n $22;
if missing('tdp_turbine_power_Max'n) then
   'BIN_tdp_turbine_power_Max'n = '_MISSING_';
else
if 'tdp_turbine_power_Max'n <= 1534.0046 then
   'BIN_tdp_turbine_power_Max'n = '01:low-1534.0046';
else 
if 'tdp_turbine_power_Max'n <= 1547.8 then
   'BIN_tdp_turbine_power_Max'n = '02:1534.0046-1547.8';
else 
if 'tdp_turbine_power_Max'n <= 1560.154 then
   'BIN_tdp_turbine_power_Max'n = '03:1547.8-1560.154';
else 
   'BIN_tdp_turbine_power_Max'n = '04:1560.154-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_turbine_power_Mean'n = 'Transformed Turbine Power';
Length 'BIN_tdp_turbine_power_Mean'n $22;
if missing('tdp_turbine_power_Mean'n) then
   'BIN_tdp_turbine_power_Mean'n = '_MISSING_';
else
if 'tdp_turbine_power_Mean'n <= 315.97038 then
   'BIN_tdp_turbine_power_Mean'n = '01:low-315.97038';
else 
if 'tdp_turbine_power_Mean'n <= 447.01838 then
   'BIN_tdp_turbine_power_Mean'n = '02:315.97038-447.01838';
else 
if 'tdp_turbine_power_Mean'n <= 552.07609 then
   'BIN_tdp_turbine_power_Mean'n = '03:447.01838-552.07609';
else 
   'BIN_tdp_turbine_power_Mean'n = '04:552.07609-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_turbine_power_StdDev'n = 'Transformed Turbine Power';
Length 'BIN_tdp_turbine_power_StdDev'n $22;
if missing('tdp_turbine_power_StdDev'n) then
   'BIN_tdp_turbine_power_StdDev'n = '_MISSING_';
else
if 'tdp_turbine_power_StdDev'n <= 353.17557 then
   'BIN_tdp_turbine_power_StdDev'n = '01:low-353.17557';
else 
if 'tdp_turbine_power_StdDev'n <= 441.67165 then
   'BIN_tdp_turbine_power_StdDev'n = '02:353.17557-441.67165';
else 
if 'tdp_turbine_power_StdDev'n <= 512.1394 then
   'BIN_tdp_turbine_power_StdDev'n = '03:441.67165-512.1394';
else 
   'BIN_tdp_turbine_power_StdDev'n = '04:512.1394-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_voltage_Max'n = 'Transformed tdp_voltage_Max';
Length 'BIN_tdp_voltage_Max'n $22;
if missing('tdp_voltage_Max'n) then
   'BIN_tdp_voltage_Max'n = '_MISSING_';
else
if 'tdp_voltage_Max'n <= 330.4285 then
   'BIN_tdp_voltage_Max'n = '01:low-330.4285';
else 
if 'tdp_voltage_Max'n <= 334.16496 then
   'BIN_tdp_voltage_Max'n = '02:330.4285-334.16496';
else 
if 'tdp_voltage_Max'n <= 337.55097 then
   'BIN_tdp_voltage_Max'n = '03:334.16496-337.55097';
else 
   'BIN_tdp_voltage_Max'n = '04:337.55097-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_voltage_Mean'n = 'Transformed tdp_voltage_Mean';
Length 'BIN_tdp_voltage_Mean'n $22;
if missing('tdp_voltage_Mean'n) then
   'BIN_tdp_voltage_Mean'n = '_MISSING_';
else
if 'tdp_voltage_Mean'n <= 324.6072 then
   'BIN_tdp_voltage_Mean'n = '01:low-324.6072';
else 
if 'tdp_voltage_Mean'n <= 327.34007 then
   'BIN_tdp_voltage_Mean'n = '02:324.6072-327.34007';
else 
if 'tdp_voltage_Mean'n <= 329.01599 then
   'BIN_tdp_voltage_Mean'n = '03:327.34007-329.01599';
else 
   'BIN_tdp_voltage_Mean'n = '04:329.01599-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_voltage_StdDev'n = 'Transformed tdp_voltage_StdDev';
Length 'BIN_tdp_voltage_StdDev'n $22;
if missing('tdp_voltage_StdDev'n) then
   'BIN_tdp_voltage_StdDev'n = '_MISSING_';
else
if 'tdp_voltage_StdDev'n <= 1.3978497 then
   'BIN_tdp_voltage_StdDev'n = '01:low-1.3978497';
else 
if 'tdp_voltage_StdDev'n <= 2.1473931 then
   'BIN_tdp_voltage_StdDev'n = '02:1.3978497-2.1473931';
else 
if 'tdp_voltage_StdDev'n <= 4.2656915 then
   'BIN_tdp_voltage_StdDev'n = '03:2.1473931-4.2656915';
else 
   'BIN_tdp_voltage_StdDev'n = '04:4.2656915-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_voltage_Var_Max'n = 'Transformed tdp_voltage_Var_Max';
Length 'BIN_tdp_voltage_Var_Max'n $22;
if missing('tdp_voltage_Var_Max'n) then
   'BIN_tdp_voltage_Var_Max'n = '_MISSING_';
else
if 'tdp_voltage_Var_Max'n <= 4.3333333 then
   'BIN_tdp_voltage_Var_Max'n = '01:low-4.3333333';
else 
if 'tdp_voltage_Var_Max'n <= 7.2581432 then
   'BIN_tdp_voltage_Var_Max'n = '02:4.3333333-7.2581432';
else 
if 'tdp_voltage_Var_Max'n <= 9.3333333 then
   'BIN_tdp_voltage_Var_Max'n = '03:7.2581432-9.3333333';
else 
   'BIN_tdp_voltage_Var_Max'n = '04:9.3333333-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_voltage_Var_Mean'n = 'Transformed tdp_voltage_Var_Mean';
Length 'BIN_tdp_voltage_Var_Mean'n $22;
if missing('tdp_voltage_Var_Mean'n) then
   'BIN_tdp_voltage_Var_Mean'n = '_MISSING_';
else
if 'tdp_voltage_Var_Mean'n <= 0.761431 then
   'BIN_tdp_voltage_Var_Mean'n = '01:low-0.761431';
else 
if 'tdp_voltage_Var_Mean'n <= 1.1544222 then
   'BIN_tdp_voltage_Var_Mean'n = '02:0.761431-1.1544222';
else 
if 'tdp_voltage_Var_Mean'n <= 2.0258327 then
   'BIN_tdp_voltage_Var_Mean'n = '03:1.1544222-2.0258327';
else 
   'BIN_tdp_voltage_Var_Mean'n = '04:2.0258327-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_voltage_Var_StdDev'n = 'Transformed tdp_voltage_Var_StdDev';
Length 'BIN_tdp_voltage_Var_StdDev'n $22;
if missing('tdp_voltage_Var_StdDev'n) then
   'BIN_tdp_voltage_Var_StdDev'n = '_MISSING_';
else
if 'tdp_voltage_Var_StdDev'n <= 0.7375526 then
   'BIN_tdp_voltage_Var_StdDev'n = '01:low-0.7375526';
else 
if 'tdp_voltage_Var_StdDev'n <= 1.3459314 then
   'BIN_tdp_voltage_Var_StdDev'n = '02:0.7375526-1.3459314';
else 
if 'tdp_voltage_Var_StdDev'n <= 2.0244465 then
   'BIN_tdp_voltage_Var_StdDev'n = '03:1.3459314-2.0244465';
else 
   'BIN_tdp_voltage_Var_StdDev'n = '04:2.0244465-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_wind_speed_Max'n = 'Transformed Turbine Wind Speed';
Length 'BIN_tdp_wind_speed_Max'n $22;
if missing('tdp_wind_speed_Max'n) then
   'BIN_tdp_wind_speed_Max'n = '_MISSING_';
else
if 'tdp_wind_speed_Max'n <= 14.56662 then
   'BIN_tdp_wind_speed_Max'n = '01:low-14.56662';
else 
if 'tdp_wind_speed_Max'n <= 16.48428 then
   'BIN_tdp_wind_speed_Max'n = '02:14.56662-16.48428';
else 
if 'tdp_wind_speed_Max'n <= 18.36895 then
   'BIN_tdp_wind_speed_Max'n = '03:16.48428-18.36895';
else 
   'BIN_tdp_wind_speed_Max'n = '04:18.36895-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_wind_speed_Mean'n = 'Transformed Turbine Wind Speed';
Length 'BIN_tdp_wind_speed_Mean'n $22;
if missing('tdp_wind_speed_Mean'n) then
   'BIN_tdp_wind_speed_Mean'n = '_MISSING_';
else
if 'tdp_wind_speed_Mean'n <= 6.5196899 then
   'BIN_tdp_wind_speed_Mean'n = '01:low-6.5196899';
else 
if 'tdp_wind_speed_Mean'n <= 7.0135853 then
   'BIN_tdp_wind_speed_Mean'n = '02:6.5196899-7.0135853';
else 
if 'tdp_wind_speed_Mean'n <= 7.8893776 then
   'BIN_tdp_wind_speed_Mean'n = '03:7.0135853-7.8893776';
else 
   'BIN_tdp_wind_speed_Mean'n = '04:7.8893776-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_wind_speed_StdDev'n = 'Transformed Turbine Wind Speed';
Length 'BIN_tdp_wind_speed_StdDev'n $22;
if missing('tdp_wind_speed_StdDev'n) then
   'BIN_tdp_wind_speed_StdDev'n = '_MISSING_';
else
if 'tdp_wind_speed_StdDev'n <= 2.5048716 then
   'BIN_tdp_wind_speed_StdDev'n = '01:low-2.5048716';
else 
if 'tdp_wind_speed_StdDev'n <= 2.9998197 then
   'BIN_tdp_wind_speed_StdDev'n = '02:2.5048716-2.9998197';
else 
if 'tdp_wind_speed_StdDev'n <= 3.4636947 then
   'BIN_tdp_wind_speed_StdDev'n = '03:2.9998197-3.4636947';
else 
   'BIN_tdp_wind_speed_StdDev'n = '04:3.4636947-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_yaw_nacelle_position_Max'n = 'Transformed Yaw/Nacelle Position';
Length 'BIN_tdp_yaw_nacelle_position_Max'n $22;
if missing('tdp_yaw_nacelle_position_Max'n) then
   'BIN_tdp_yaw_nacelle_position_Max'n = '_MISSING_';
else
if 'tdp_yaw_nacelle_position_Max'n <= 354 then
   'BIN_tdp_yaw_nacelle_position_Max'n = '01:low-354';
else 
if 'tdp_yaw_nacelle_position_Max'n <= 357 then
   'BIN_tdp_yaw_nacelle_position_Max'n = '02:354-357';
else 
   'BIN_tdp_yaw_nacelle_position_Max'n = '04:357-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_yaw_nacelle_position_Mea'n = 'Transformed Yaw/Nacelle Position';
Length 'BIN_tdp_yaw_nacelle_position_Mea'n $22;
if missing('tdp_yaw_nacelle_position_Mean'n) then
   'BIN_tdp_yaw_nacelle_position_Mea'n = '_MISSING_';
else
if 'tdp_yaw_nacelle_position_Mean'n <= 142.72612 then
   'BIN_tdp_yaw_nacelle_position_Mea'n = '01:low-142.72612';
else 
if 'tdp_yaw_nacelle_position_Mean'n <= 177.36864 then
   'BIN_tdp_yaw_nacelle_position_Mea'n = '02:142.72612-177.36864';
else 
if 'tdp_yaw_nacelle_position_Mean'n <= 211.93185 then
   'BIN_tdp_yaw_nacelle_position_Mea'n = '03:177.36864-211.93185';
else 
   'BIN_tdp_yaw_nacelle_position_Mea'n = '04:211.93185-high';

* Transformation Method = QUANTILE ;
Label 'BIN_tdp_yaw_nacelle_positio_StdD'n = 'Transformed Yaw/Nacelle Position';
Length 'BIN_tdp_yaw_nacelle_positio_StdD'n $22;
if missing('tdp_yaw_nacelle_positio_StdDev'n) then
   'BIN_tdp_yaw_nacelle_positio_StdD'n = '_MISSING_';
else
if 'tdp_yaw_nacelle_positio_StdDev'n <= 65.229518 then
   'BIN_tdp_yaw_nacelle_positio_StdD'n = '01:low-65.229518';
else 
if 'tdp_yaw_nacelle_positio_StdDev'n <= 88.960622 then
   'BIN_tdp_yaw_nacelle_positio_StdD'n = '02:65.229518-88.960622';
else 
if 'tdp_yaw_nacelle_positio_StdDev'n <= 103.64541 then
   'BIN_tdp_yaw_nacelle_positio_StdD'n = '03:88.960622-103.64541';
else 
   'BIN_tdp_yaw_nacelle_positio_StdD'n = '04:103.64541-high';
*------------------------------------------------------------*;
*Nodeid: _35CMXU8SLDQYM4L2SBXHOUFIR;
*------------------------------------------------------------*;
   /*---------------------------------------------------------
     Generated SAS Scoring Code
     Date: 21Jun2021:19:45:18
     -------------------------------------------------------*/

   drop _badval_ _linp_ _temp_ _i_ _j_;
   _badval_ = 0;
   _linp_   = 0;
   _temp_   = 0;
   _i_      = 0;
   _j_      = 0;
   drop MACLOGBIG;
   MACLOGBIG= 7.0978271289338392e+02;

   array _xrow_99871156_0_{18} _temporary_;
   array _beta_99871156_0_{18} _temporary_ (    8071.82087656678
           2796.89839796702
           1510.78822190749
          -35.2766405530774
           13.1610543229244
          -7.69673128701602
           9.10829030062611
           0.05594968366581
           63.6852501509338
          -47.0319793397088
           65.4988315496999
           2.93982601570785
           2904.06170998344
                          0
          -1173.67353977043
                          0
           718.820680964112
                          0);

   length _ctmp_0_ $22; drop _ctmp_0_;
   _ctmp_0_ = left(trim(put(BIN_tdp_blade_angle_3_set_Max,$22.)));
   length _BIN_SumOilTemp4320_ $22; drop _BIN_SumOilTemp4320_;
   _BIN_SumOilTemp4320_ = left(trim(put(BIN_SumOilTemp4320,$22.)));
   length _ctmp_1_ $22; drop _ctmp_1_;
   _ctmp_1_ = left(trim(put(BIN_tdp_blade_angle_2_set_Max,$22.)));
   if missing(SumDamage4320)
      or missing(tdp_air_temp_Mean)
      or missing(tdp_hydraulic_pressure_Mean)
      or missing(pGB1)
      or missing(tdp_voltage_Max)
      or missing(tdp_blade_angle_2_set_Mean)
      or missing(tdp_wind_speed_Max)
      or missing(tdp_yaw_nacelle_position_Mean)
      or missing(tdp_blade_angle_2_set_StdDev)
      or missing(tdp_state_fault_Max)
      or missing(tdp_temp_gen_bearing_nde_Mean)
      then do;
         _badval_ = 1;
         goto skip_99871156_0;
   end;

   do _i_=1 to 18; _xrow_99871156_0_{_i_} = 0; end;

   _xrow_99871156_0_[1] = 1;

   _xrow_99871156_0_[2] = pGB1;

   _xrow_99871156_0_[3] = SumDamage4320;

   _xrow_99871156_0_[4] = tdp_air_temp_Mean;

   _xrow_99871156_0_[5] = tdp_blade_angle_2_set_Mean;

   _xrow_99871156_0_[6] = tdp_blade_angle_2_set_StdDev;

   _xrow_99871156_0_[7] = tdp_hydraulic_pressure_Mean;

   _xrow_99871156_0_[8] = tdp_state_fault_Max;

   _xrow_99871156_0_[9] = tdp_temp_gen_bearing_nde_Mean;

   _xrow_99871156_0_[10] = tdp_voltage_Max;

   _xrow_99871156_0_[11] = tdp_wind_speed_Max;

   _xrow_99871156_0_[12] = tdp_yaw_nacelle_position_Mean;

   _temp_ = 1;
   select (_BIN_SumOilTemp4320_);
      when ('01:low-0') _xrow_99871156_0_[13] = _temp_;
      when ('04:0-high') _xrow_99871156_0_[14] = _temp_;
      otherwise do; _badval_ = 1; goto skip_99871156_0; end;
   end;

   _temp_ = 1;
   select (_ctmp_1_);
      when ('01:low-85') _xrow_99871156_0_[15] = _temp_;
      when ('04:85-high') _xrow_99871156_0_[16] = _temp_;
      otherwise do; _badval_ = 1; goto skip_99871156_0; end;
   end;

   _temp_ = 1;
   select (_ctmp_0_);
      when ('01:low-85') _xrow_99871156_0_[17] = _temp_;
      when ('04:85-high') _xrow_99871156_0_[18] = _temp_;
      otherwise do; _badval_ = 1; goto skip_99871156_0; end;
   end;

   do _i_=1 to 18;
      _linp_ + _xrow_99871156_0_{_i_} * _beta_99871156_0_{_i_};
   end;

   skip_99871156_0:
   length I_targetGB0 $1;
   label I_targetGB0 = 'Into: targetGB0';
   array _levels_99871156_{2} $ 1 _TEMPORARY_ ('1'
   ,'0'
   );
   label P_targetGB01 = 'Predicted: targetGB0=1';
   if (_badval_ eq 0) and not missing(_linp_) then do;
      if (_linp_ > 0) then do;
         P_targetGB01 = 1 / (1+exp(-_linp_));
      end; else do;
         P_targetGB01 = exp(_linp_) / (1+exp(_linp_));
      end;
      P_targetGB00 = 1 - P_targetGB01;
      if P_targetGB01 >= 0.5                  then do;
         I_targetGB0 = _levels_99871156_{1};
      end; else do;
         I_targetGB0 = _levels_99871156_{2};
      end;
   end; else do;
      _linp_ = .;
      P_targetGB01 = .;
      P_targetGB00 = .;
      I_targetGB0 = ' ';
   end;


   *------------------------------------------------------------*;
   * Initializing missing posterior and classification variables ;
   *------------------------------------------------------------*;
   if "P_targetGB00"n = . then "P_targetGB00"n =0.9281045752;
   if "P_targetGB01"n = . then "P_targetGB01"n =0.0718954248;
   if missing('I_targetGB0'n) then do;
      drop _P_;
      _P_= 0.0 ;
      if 'P_targetGB01'n > _P_ then do;
      _P_ = 'P_targetGB01'n;
      'I_targetGB0'n = '1';
      end;
      if 'P_targetGB00'n > _P_ then do;
      _P_ = 'P_targetGB00'n;
      'I_targetGB0'n = '0';
      end;
   end;
*------------------------------------------------------------*;
* Generating fixed output names;
*------------------------------------------------------------*;
Length EM_EVENTPROBABILITY 8;
LABEL EM_EVENTPROBABILITY = "Probability for targetGB0 =1";
EM_EVENTPROBABILITY ='P_targetGB01'n;
LENGTH EM_CLASSIFICATION $8;
LABEL EM_CLASSIFICATION= "Predicted for targetGB0";
EM_CLASSIFICATION ='I_targetGB0'n;
Length EM_PROBABILITY 8;
LABEL EM_PROBABILITY = "Probability of Classification";
EM_PROBABILITY = max(
'P_targetGB01'n,
'P_targetGB00'n);


run;


proc freq data=temp; table targetGB0; run;

proc means data=temp; var em_EventProbability; run;

data temp2;
   set temp;
   if em_EventProbability ge 0.5 then class=1; else class=0;
   if em_EventProbability ge 0.05 then class2=1; else class2=0;
run;

proc freq; table class*targetGB0; run;
proc freq; table class2*targetGB0; run;